Graphics.prototype.setFontArial = function () {
  // Actual height 16 (15 - 0)
  // 1 BPP
  return this.setFontCustom(
    atob(
      "AAAAAAAAAAAAAP+w/7DwAAAA4AD4APAA8AD4AAAADMgN/D/4f8Bs+A/4f+D8wAzAAAAYYHx4fjjnHP/+Yxhz+DHwAEAAAAAAfgB+AEcMfjw88APADwA88HH4QYwB2AH4ACAAAABgAfA/+H8Ybxhv2H34OPAB+AGYAADwAPgA8AAAAAAAD/g//ngPQAEAAAAA4AN8Hx/8B/gAADAAPAB8AHwAPAAwAAAAAgAGAAYABgA/wD/ABgAGAAYAAAAAAAA0ADwAAAGAA4ADgAOAA4AAAAAAADAAMAAAADwD+D/AfAAAAA/AP/B/+GAYYBhgGH/4P/ADAAAAAAAIABgAOAB/+H/4AAAIGDg4eHhg+GHYY5h/GD4YAAAAIDhweDhjGGccfxh/+D3wAEAAAAHAB8APwD3AccD/8P/wAcAAgAAAAEB+8P5wzDDMOMwwz/DH4AGAAAAPwD/wf/hmGGYcZhh3+DPwAMAAAMAAwADA8MPwz8D+APgA4ADAAAAAAOA98H/4ZxhnHGcYf/g98ABAAAAeAD8wf7hhmGGYYZh/+D/gB4AAAAAAGDAYMAAAAAAYNBg8AAAGAAcADwAPAB+AGYA5wDDAMMAAAAkAGYAZgBmAGYAZgBmAGYAZgAAAIEAwwDnAGYAdgA+ADwAPAAYAAAAQADgAeABg2GPYZ9h/ADwAAAAAQAf4H/w4TnP3Z/tuG2wb7Dlv+W/7b5twOzz2H+4DDAAAAHAB8A/gf4D5gPGA/4AfgAfwAPAAMAAAAAD/8P/wxjDGMMYwzjD/cH/wM+AAAAMAH+A/8HA4YBhgGGAYYBhwODjwGGAAAAAA//D/8MAwwDDAMMAw4HDx8H/gH4AAAAAA//D/8MYwxjDGMMYwxjDGMMQwAAAAAP/w//DGAMYAxgDGAMYAxgAAAAEAH+A/8HA4YBhgGGGYY5hjmHu4O/AJ8AAAAAD/8P/wDgAOAA4ADgAOAP/w//D/8AAAAAD/8P/wAAAA4ADwADAAOAAw//D/4AAAAAD/8P/wDwAeAD8Af8Dx4ODwwDCAEAAAAAD/8P/wADAAMAAwADAAMAAwAAAAAP/w//D8AD+AB/AA8APwH8D+AP/w//D/8AAAAAD/8P/w+AA8AB8AB4AB4P/w//D/8AAAAwAf4D/wcDhgGGAYYBhgGHA4fHgf4A/AAAAAAP/w//DHAMcAxwDGAMYA/gB8AAAAAwAf4D/wcDhgGGAYYHhgOHA4PPgf/A/MAAAAAP/w//DGAMYAxgDHAMfA/+B88DAwABAAAABAPHB+eGYYZxhnHGMYc5g5+BnwAADAAMAAwADAAP/w//DAAMAAwADAAAAAAAD/wP/gAHAAMAA4ADAAMP/w/+D/AAAAwAD4AH8AD8AB8ABwA/AfgP4A8ACAAAAA4AD+AH/gA/AD8B/g/gDwAP4AP+AD8APwP+D+AOAAAACAEMBw8PB7wD+AHwA/gHng4PDAMAAQAADAAOAA+AA8AB/wD/AeAHgA8ADAAIAAAAAAMMDwwfDDsM8w3jD8MPAw4DDAMAAAAAD/////wAcAAPAAfwAP8AD8AADAAsAH/////gAAAwAPAH4A8AB8AB8ABwAAAAADAAMAAwADAAMAAwADAAMAAwAAAABgAHAAMAAAAADgDfAd8BmwG7AbMB/wD/AAEAAAAAD/8P/wGDAYMBgwH/AP4AOAAAADwA/gH/AYMBg4GDAc8ATgAAAHwA/gHvAYMBgwHDD/8P/wAAADwA/gH/AbMBswGzAfcA9gAwAAAAwAf/h/+GwAAAAHwA/uHvYYNxgzHDYf/h/8AAAAAP/w//AYABgAGAAf8A/wAAAAAN/w3/AAAAAH3/7f/AAAAAD/8P/wBwAPwB3wGHAQMAAAAAD/8P/wAAAAAB/wH/AYABgAHAAf8A/wGAAYAB/wH/AH8AAAAAAf8B/wGAAYABgAH/AP8AAAB8AP4B7wGDAYMBgwH/AP4AOAAAAAAB//H/4YMBgwGDAf8A/gA4AAAAfAD+Ae8BgwGDAcMB/+H/4AAAAAH/Af8BgAGAAAAARAH3AfcBuwG7Ad8A3wAOAAABgAf/D/8BgwAAAAAB/wH/AAMAAwADAf8B/wAAAYAB8AD+AB8AHwD+AfABgAAAAcAB/AB/AA8A/wHwAfwAfwAfAP4B8AGAAAABAQHHAf8AfAB8Ae8BxwEBAAABgCHwcP5wH+APwH4B8AHAAAABgwGHAZ8BvwH7AeMBwwGDAAAADAA+B//34/4AEAAAAAf/9//wAAYAFwB39/P/4BwAAABwAGAA4ADgAGAAcABwAHAAYAAAA="
    ),
    32,
    atob(
      "BAUGCgoPCwQGBgcKBAYEBQoHCQoKCgoKCgoEBAoKCgkRDAsMDAsKDQwECAwKDgwNCw0NCwsMDBAMDAsFBQUICgUKCgkJCgUJCQQECQQOCQoKCQYJBQkJDQkJCQYEBgo="
    ),
    16 | 65536
  );
};
